### ISSUE TITLE
GrdFile is not able to read my grid file

### ISSUE THREAD

**Issue by ghost** [Carlisle345748/Delft3D-Toolbox#1]
Hello,
[lombok_dep.txt](https://github.com/Carlisle345748/Delft3D-Toolbox/files/6555202/lombok_dep.txt)
[lombok_enc.txt](https://github.com/Carlisle345748/Delft3D-Toolbox/files/6555208/lombok_enc.txt)
[lombok_grd.txt](https://github.com/Carlisle345748/Delft3D-Toolbox/files/6555209/lombok_grd.txt)

_GrdFile.py_ is not able to read my grid file. It gives the following error message:

**ValueError: cannot reshape array of size 0 into shape (348,319)**

I have tried several grid files to see if a single file was the issue, but I had some trouble each time regardless of the grid format (circular, curvilinear, etc.). I have created them using RGFGRID, no 3rd party software.

I'm attaching my files and I'd be glad if you can tell me what's wrong. Since that their usual format is not supported here (.grd, .enc, .dep), I'm attaching them as plain text files.

Thanks for your help.

**Comment by Carlisle345748** [comment]
The lombok_grd.txt file you provided seems to lack Y coordinate data. So reshaping the array of zero dimension failed.

**Comment by Carlisle345748** [comment]
> Hello,
> [lombok_dep.txt](https://github.com/Carlisle345748/Delft3D-Toolbox/files/6555202/lombok_dep.txt)
> [lombok_enc.txt](https://github.com/Carlisle345748/Delft3D-Toolbox/files/6555208/lombok_enc.txt)
> [lombok_grd.txt](https://github.com/Carlisle345748/Delft3D-Toolbox/files/6555209/lombok_grd.txt)
> 
> _GrdFile.py_ is not able to read my grid file. It gives the following error message:
> 
> **ValueError: cannot reshape array of size 0 into shape (348,319)**
> 
> I have tried several grid files to see if a single file was the issue, but I had some trouble each time regardless of the grid format (circular, curvilinear, etc.). I have created them using RGFGRID, no 3rd party software.
> 
> I'm attaching my files and I'd be glad if you can tell me what's wrong. Since that their usual format is not supported here (.grd, .enc, .dep), I'm attaching them as plain text files.
> 
> Thanks for your help.

The lombok_grd.txt file you provided seems to lack Y coordinate data. So reshaping the array of zero dimension failed.

**Comment by ghost** [comment]
I've attached the original files to the e-mail. You can take a look 
yourself at the original grid file, which has y-coordinate info if you 
go below in the file (starting at line 22280). Furthermore I have 
already used these files to run simulations, and they worked fine. Rigth 
now I'm just trying to develop a python code to read HYCOM and TPXO data 
and transfer them into the boundary condition files of Delft3D-FLOW 
models.

I am not sure about the file structures used for the other (older/newer) 
Delft3D versions but I just thought my Delft3D RGFGRID version was 
incompatible with your code.

Anyway, thanks for your time.

---

---
Kadir Orhan, PhD
Coastal Research Laboratory
Research and Technology Centre Westcoast (FTZ)
---
Christian Albrechts University
Otto-Hahn-Platz 3, R.9
24118
Kiel, Germany
---
Office: +49-(0)431-880-3730

Am 2021-05-30 08:23, schrieb Carlisle345748:

>> Hello,
>> lombok_dep.txt [1]
>> lombok_enc.txt [2]
>> lombok_grd.txt [3]
>> 
>> _GrdFile.py_ is not able to read my grid file. It gives the following 
>> error message:
>> 
>> ValueError: cannot reshape array of size 0 into shape (348,319)
>> 
>> I have tried several grid files to see if a single file was the issue, 
>> but I had some trouble each time regardless of the grid format 
>> (circular, curvilinear, etc.). I have created them using RGFGRID, no 
>> 3rd party software.
>> 
>> I'm attaching my files and I'd be glad if you can tell me what's 
>> wrong. Since that their usual format is not supported here (.grd, 
>> .enc, .dep), I'm attaching them as plain text files.
>> 
>> Thanks for your help.
> 
> The lombok_grd.txt file you provided seems to lack Y coordinate data. 
> So reshaping the array of zero dimension failed.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [4], or unsubscribe 
> [5].


Links:
------
[1] 
https://github.com/Carlisle345748/Delft3D-Toolbox/files/6555202/lombok_dep.txt
[2] 
https://github.com/Carlisle345748/Delft3D-Toolbox/files/6555208/lombok_enc.txt
[3] 
https://github.com/Carlisle345748/Delft3D-Toolbox/files/6555209/lombok_grd.txt
[4] 
https://github.com/Carlisle345748/Delft3D-Toolbox/issues/1#issuecomment-850949332
[5]

**Comment by ghost** [comment]
Original files couldn't be delivered because of the server limitations, but you can see the y-coordinate info in the grid file with the txt format I have provided. It begins halfway through the file. And like I said, the file is created by the Delft3D itself (RGFGRID) and already used to run simulations.

**Comment by Carlisle345748** [comment]
Thank you so much for providing the original grid file. I found the problem in the regexp for parsing numbers. I have fixed that problem. You can try again to see whether it works well.

**Comment by korhan-droid** [comment]
Yes, now it works well. Thank you very much.

**Comment by ghost** [comment]
Yes, now it works well. Thank you very much.
