### ISSUE TITLE
grd.plot() unexpected behaviour with pcolormesh

### ISSUE THREAD

**Issue by VeckoTheGecko** [Carlisle345748/Delft3D-Toolbox#3]
Hello. Thanks for creating this package (and making it open source). I have been experimenting with the documentation notebook.

I realised that when I rerun the cells in the `Visualize the grid.` section that the plots don't display as intended (see the images at the bottom).

I've done some preliminary hunting for the bug, but haven't found it yet (though I'm reasonably certain its in `GridFile.py` in `GrdFile.plot()`.

My questions are:
- Was the documentation notebook created after the last changes to the `GridFile.plot()` method?
- Do you have a record of which version of matplotlib (+ other packages) you were using during development?

# Images
Going from
![output](https://user-images.githubusercontent.com/36369090/182010886-0a176235-05e9-4f82-9b47-74f75f06aeea.png)
and
![output](https://user-images.githubusercontent.com/36369090/182010872-25563b21-53f5-4014-af8e-6c570d430181.png)

---
Breaking and resulting in:
![output](https://user-images.githubusercontent.com/36369090/182010930-d9595db5-2d42-4431-a28c-46de68e2134f.png)
and 
![output2](https://user-images.githubusercontent.com/36369090/182010933-8fbe1822-a7c2-4653-8bfb-f50c9d48cd7e.png)

**Comment by VeckoTheGecko** [comment]
By the way, I understand if you don't want to actively maintain this package and monitor issues etc.. Just let me know, I'm happy to work off my fork implementing fixes and features.

**Comment by Carlisle345748** [comment]
Sorry, I don't remember the version of the packages when I developed this. I have been kind of busy recently but can look into this problem later.

> By the way, I understand if you don't want to actively maintain this package and monitor issues etc.. Just let me know, I'm happy to work off my fork implementing fixes and features.

That's true, I don't have enough time to maintain this package now. Feel free to work on your fork. Thanks for your contribution!
